version: '3'

services:
  backend:
    image: kieransmith/session-spawner-backend:v1.2
    ports:
      - "5000:5000"
    restart: always

  client:
    image: kieransmith/session-spawner-client:v1.1
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

